name: TorchDonation
version: ${project.version}
main: net.gooday2die.torchdonation.TorchDonation
api-version: 1.18
authors: [ Gooday2die ]
description: A Donation Plugin for Korean Minecraft Servers
website: https://github.com/gooday2die/TorchDonation

commands:
  test:
    description: test
    usage: /<command>
    permission: TorchDonation.test