# Torch Donation Plugin By Gooday2die
# https://github.com/gooday2die/TorchDonation
#
# config.yml에 적힌 내용 안읽고 질문하면 답변 안합니다.
# 사용시 라이센스 지우지 마시기 바랍니다.

# 후원 성공시 실행할 명령어
# Placeholder가 있습니다.
# %amount% : 후원한 금액
# %user% : 후원한 유저
# 밑의 두 케이스의 예시는 다음과 같습니다
# /say Gooday2die 님이 10000 만큼 후원하셨습니다!
# /lp user Gooday2die group add VIP
# /coin give Gooday2die 10000
rewardCommands:
  [
  "say %user% 님이 %amount% 만큼 후원하셨습니다!",
  "lp user %user% group add VIP",
  "coin give %user% %amount%"
  ]
# 후원시 서버 전체에 알림을 할지 말지에 대한 여부입니다.
broadcastDonation: true


# DB 설정
# MYSQL DB를 사용할지 여부입니다. DB가 뭔지 모르시면 false 로 놔주세요.
# 만약 MYSQL DB를 사용하지 않는다면 SQLITE3 으로 저장합니다
useMySQL: false
# MYSQL DB 의 IP 입니다
dbIP: "null"
# MYSQL DB 의 username 입니다
dbID: "null"
# MYSQL DB 의 비밀번호입니다
dbPW: "null"
# MYSQL DB 의 DB 이름입니다
dbName: "null"
# MYSQL DB 에서 사용할 prefix 이름입니다.
dbTablePrefix: "null"