name: TorchDonation
version: ${project.version}
main: net.gooday2die.torchdonation.TorchDonation
api-version: 1.18
authors: [ Gooday2die ]
description: A Donation Plugin for Korean Minecraft Servers
website: https://github.com/gooday2die/TorchDonation

commands:
  donate:
    description: 문화상품권 코드를 후원합니다
    usage: /<command> 문화상품권 코드
    permission: TorchDonation.donate

  redeem:
    description: 문화상품권 코드를 후원합니다
    usage: /<command> 문화상품권 코드
    permission: TorchDonation.donate

  후원:
    description: 문화상품권 코드를 후원합니다
    usage: /<command> 문화상품권 코드
    permission: TorchDonation.donate

  문상:
    description: 문화상품권 코드를 후원합니다
    usage: /<command> 문화상품권 코드
    permission: TorchDonation.donate

  treload:
    description: TorchDonation의 Config.yml 을 reload 합니다
    usage: /<command>
    permission: TorchDonation.reload